### ISSUE TITLE
Why yet another ngx-matomo?

### ISSUE THREAD

**Issue by kulfoniasty** [EmmanuelRoux/ngx-matomo-client#13]
Hey @EmmanuelRoux! I have just came across your fantastic library but I struggle to answer myself a question: why have you started yet another ngx-matomo?

Is it because the original ngx-matomo is orphaned and no longer maintained? I tried adopting it but I failed and ended up using RC version which was still far from perfect. I would like to know your story and commitment to maintaining this better ngx-matomo because it looks very promising.

**Comment by EmmanuelRoux** [comment]
Hi @kulfoniasty 

Thank you for your interest, that's a very good question.
The story is that for many months/years, the "original" ngx-matomo library owner wasn’t maintaining it, neither he seemed responding to issues or pull requests (I think that's why there are so many forks of it...)

Because I was working on some Angular 10+ apps and couldn't wait for updates, I ended up developing my own tool for internal use. As it was quite stable and many people were asking for updates (like support for Angular 9 +), I eventually decided to release it publicly

While my lib is obviously inspired by existing ones, I choose to start a new project from scratch in order to create a clean codebase using up-to-date tools (including Angular CLI with Ivy support)

I would also like to provide a bit more integration with the « Angular way » of app development. Currently most Matomo clients are just a facade for the native Matomo JS api : they only provide an Angular service with Matomo methods.
This does not solve many issues when using Matomo with single-page apps, such as automatic tracking of page views and dynamically added content (which is the essence of Angular components)
My goal is to provide some more useful integration and seamless SPA tracking : for example, directives for tracking links, events, content impressions, and so on. Such features should arrive very soon (before the end of the summer) 😉 

Please feel free to fill in new issues if you encounter difficulties or suggest some pull requests!

**Comment by kulfoniasty** [comment]
Thanks for a detailed response. This is definitely a great reason to start a new library and since it is already catching some attention and npm downloads I believe bright future is ahead of your lib. I am keeping my fingers crossed and I hope to find some time to fill in issues and drop PR or two. 

Good luck!
